version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
