name: build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      -
        name: Build testing container
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.development_builder.outputs.name }}
          target: development
          load: true
          tags: plants-client-testing:latest
      -
        name: Run tests
        uses: addnab/docker-run-action@v1
        with:
          image: plants-client-testing:latest
          shell: sh
          run: sh /app/run_tests_ci ${{ github.sha }} ${{ secrets.CODECOV_TOKEN }}
      -
        name: Set up production Docker Buildx
        id: production_builder_test
        uses: docker/setup-buildx-action@v1
      -
        name: Build production container # This is to know that the production build works
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.production_builder_test.outputs.name }}
          target: production
          tags: namelivia/plants-client:latest
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
      -
        name: Set up production Docker Buildx
        id: production_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Determine Docker tag
        id: docker_tag
        run: |
          # This run block will now only execute if the job's 'if' condition passed,
          # meaning we are definitely on a push to 'main'.
          echo "TAG=latest" >> $GITHUB_ENV
      -
        name: Build and push production container
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.production_builder.outputs.name }}
          target: production
          tags: namelivia/plants-client:${{ env.TAG }}
